# Generated by Django 4.2.5 on 2023-09-27 14:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('std', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('min', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('max', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
    ]
